### ISSUE TITLE
保存模型报错

### ISSUE THREAD

**Issue by Super-Louis** [foamliu/Machine-Translation#2]
你好，我用你之前的模型在训练完保存的时候报pickle dump error，请问你有遇到吗

**Comment by foamliu** [comment]
没有。

**Comment by west-easts** [comment]
你好，请问下samples_path = 'data/samples_train.json'
                    samples = json.load(open(samples_path, 'r'))
samples_train.json是什么样的数据？没有找到原始的数据

**Comment by charlesXu86** [comment]
> 你好，我用你之前的模型在训练完保存的时候报pickle dump error，请问你有遇到吗

可以分享一下这个数据集吗？

**Comment by charlesXu86** [comment]
> 手动创建一个 models 目录再试试看？

您好，可以分享一下数据集吗？

**Comment by wuyw** [comment]
分享一下数据集吧？

**Comment by foamliu** [comment]
在 README.md 里有链接的。

**Comment by charlesXu86** [comment]
那个报名已经结束了，下载不了数据了


Thanks&Best Regards.
Charles
在2019年1月14日 13:44，刘杨<notifications@github.com> 写道：

在 README.md 里有链接的。
