### ISSUE TITLE
英中翻译数据集

### ISSUE THREAD

**Issue by DawnDoe** [foamliu/Machine-Translation#3]
数据集已无法下载了，也没有WORDMAP_zh.json和WORDMAP_en.json两个文件，请问可以分享下数据吗？

**Comment by wyx518** [comment]
同求

**Comment by Li-rr** [comment]
> 数据集已无法下载了，也没有WORDMAP_zh.json和WORDMAP_en.json两个文件，请问可以分享下数据吗？

百度搜一搜，有个网站有

**Comment by foamliu** [comment]
WORDMAP_zh.json和WORDMAP_en.json两个文件是 pre_process.py 生成的。若还找不到数据，可发邮件给 foamliu@yeah.net.
